**Question:**

**Case Study: Using Stents to Prevent Strokes**

An experiment is designed to study the effectiveness of stents in treating patients at risk of stroke (Chimowitz et al., 2011). Stents are small mesh tubes placed inside narrow or weak arteries to assist in patient recovery after cardiac events and reduce the risk of additional heart attacks or deaths. Many doctors hoped that there would be similar benefits for patients at risk of stroke.

Researchers conducted an experiment with 451 at-risk patients, randomly assigning them to one of two groups:

**Treatment group:** Patients received a stent and medical management, including medications, management of risk factors, and help in lifestyle modification.

**Control group:** Patients received the same medical management but no stents.
Researchers studied the effect of stents at two time points: 30 days after enrollment and 365 days after enrollment.

The dataset includes two CSV files, stent30.csv and stent365.csv, representing patient outcomes at 30 days and 365 days, respectively. Each row contains a patient's group (treatment or control) and outcome (stroke or no event).

Tasks:

Load the datasets and create pivot tables to summarize the outcomes at 30 days and 365 days.
    
Merge the two pivot tables into a single DataFrame.
    
Calculate and print the proportion of patients who had a stroke in the treatment and control groups at 30 days and 365 days intervals.

In [1]:
import pandas as pd

In [3]:
stent30 = pd.read_csv(r"C:\Users\dell\Downloads\Python\case study\00_all_csv_files\csv\stent30.csv")
stent365 = pd.read_csv(r"C:\Users\dell\Downloads\Python\case study\00_all_csv_files\csv\stent365.csv")

In [4]:
stent30.head(5)

       group outcome
0  treatment  stroke
1  treatment  stroke
2  treatment  stroke
3  treatment  stroke
4  treatment  stroke

In [5]:
stent365.head(5)

       group outcome
0  treatment  stroke
1  treatment  stroke
2  treatment  stroke
3  treatment  stroke
4  treatment  stroke

In [6]:
stent30_df = stent30.set_index('group')

In [7]:
stent30_df

            outcome
group
treatment    stroke
treatment    stroke
treatment    stroke
treatment    stroke
treatment    stroke
...             ...
control    no event
control    no event
control    no event
control    no event
control    no event

[451 rows x 1 columns]

In [8]:
stent365_df = stent365.set_index('group')

In [9]:
stent365_df

            outcome
group
treatment    stroke
treatment    stroke
treatment    stroke
treatment    stroke
treatment    stroke
...             ...
control    no event
control    no event
control    no event
control    no event
control    no event

[451 rows x 1 columns]

In [10]:
treatment_group = stent30_df.loc['treatment']

In [11]:
treatment_group

            outcome
group
treatment    stroke
treatment    stroke
treatment    stroke
treatment    stroke
treatment    stroke
...             ...
treatment  no event
treatment  no event
treatment  no event
treatment  no event
treatment  no event

[224 rows x 1 columns]

In [14]:
# For 30 days data
stent30_reset = stent30_df.reset_index()
stent30_pivot = stent30_reset.pivot_table(index='group', columns='outcome', aggfunc='size', fill_value=0)

# For 365 days data
stent365_reset = stent365_df.reset_index()
stent365_pivot = stent365_reset.pivot_table(index='group', columns='outcome', aggfunc='size', fill_value=0)

print("30 Days Summary:")
print(stent30_pivot)

print("\n365 Days Summary:")
print(stent365_pivot)

30 Days Summary:
outcome    no event  stroke
group
control         214      13
treatment       191      33

365 Days Summary:
outcome    no event  stroke
group
control         199      28
treatment       179      45

In [19]:
merged_df = stent30_pivot.join(stent365_pivot, lsuffix='_30days', rsuffix='_365days')
merged_df

outcome    no event_30days  stroke_30days  no event_365days  stroke_365days
group
control                214             13               199              28
treatment              191             33               179              45

In [17]:
# Calculate the number of stroke cases and total patients in the treatment group
stroke_cases_treatment = stent365_pivot.loc['treatment', 'stroke']
total_patients_treatment = stent365_pivot.loc['treatment'].sum()

# Calculate the number of stroke cases and total patients in the control group
stroke_cases_control = stent365_pivot.loc['control', 'stroke']
total_patients_control = stent365_pivot.loc['control'].sum()


# Compute the proportion
proportion_stroke_treatment = (stroke_cases_treatment / total_patients_treatment)*100
proportion_stroke_control = (stroke_cases_control  / total_patients_control) * 100

print(f"Proportion of patients in the treatment group who had a stroke by the end of the first year: {proportion_stroke_treatment:.0f}%")
print(f"Proportion of patients in the treatment group who had a stroke by the end of the first year: {proportion_stroke_control:.0f}%")

Proportion of patients in the treatment group who had a stroke by the end of the first year: 20%
Proportion of patients in the treatment group who had a stroke by the end of the first year: 12%